### PR TITLE
Add v0.22 schemas

### PR DESCRIPTION
**Pull request by CyberHoward**

### CODE REVIEW

**Review by dalechyn — APPROVED** [review]
merge conflict needs to get resolved

**Review by dalechyn — CHANGES_REQUESTED** [review]
crap, getting this old error again:
`Token "ResultOfArrayOfBinaryOrErrorResponse" does not exist.`

**Review by dalechyn — APPROVED** [review]
https://github.com/AbstractSDK/schemas/pull/42#pullrequestreview-2046229617

nevermind, the hotfix I made previously is in the asynchronous schema resolution logic thus won't fail when this will be merged.

**Comment by Buckram123** [comment]
> merge conflict needs to get resolved

Yeah 0.20 and 0.21 schemas should not be included in this PR, I'll fix it

**Comment by Buckram123** [comment]
> > merge conflict needs to get resolved
> 
> Yeah 0.20 and 0.21 schemas should not be included in this PR, I'll fix it

There were many conflicts and too much hussle to revert 0.21 and 0.20 schemas

**Pull request closed without merging**
